### ISSUE TITLE
Add Nerd Font patches to the patcher?

### ISSUE THREAD

**Issue by rescenic** [ofolis/consolig#13]
Can you add Nerd Font patches to your patcher?

**Comment by akhilesh-balaji** [comment]
+1

This would add in powerline support as well. I'm just looking for one font with programming ligatures as well as powerline support. Something like a Consolas version of Fira Code.

Right now, I have 3 versions of Consolas installed: Consolig, Consolas NF, and Consolas.

It would be nice if at least one would have all in one programming support: A range of ligatures like Fira Code, Nerd Fonts, powerline support, and math writing.

**Comment by akhilesh-balaji** [comment]
@rescenic I believe I've found a way to do this.
Simply download the files for Consolas Powerline, which has NF support: https://github.com/Znuff/consolas-powerline
Then rename them appropriately at put them in the input folder, and run the build

Hope this helps!

**Comment by ofolis** [comment]
I will look into the lift on this for sure. As I mentioned in the readme, this was always supposed to be my "first pass" ... but like a lot of projects, it hasn't gotten a lot of love for a while. I'll round back soon and dive into some of these requests. I like this idea though 👍 .

**Comment by ofolis** [comment]
Hey all, got a big win out in https://github.com/ofolis/consolig/releases/tag/v0.4.0 with the main TrueType building. I'll be looking into this stuff next.

In the mean time, if you have a lower-res display, you should see some solid improvements.

**Comment by ofolis** [comment]
v0.5.0 gets us most of the way to where you're requesting. We are still missing Powerline and math, but that is comparatively much simpler than the lift to get 0.5 out. Check out the readme and let me know. Thanks!

**Comment by ofolis** [comment]
Big news today @akhilesh-balaji, I have added Powerline support just now in version 0.6.
![image](https://user-images.githubusercontent.com/768539/108805295-c57b2880-756d-11eb-809a-3d3066ae4c9d.png)

Two versions in one day 😅

**Comment by akhilesh-balaji** [comment]
@ofolis 👏👏
Great! I can't wait to try it out. I will download 0.6 right away.

**Comment by ofolis** [comment]
I'm going to close this in favor of #3 

I've decided that the goal of Consolig v1 is feature parity with FiraCode along all Consolas styles. This issue is specifically requesting extended scope based upon Nerd Fonts, but matching FiraCode should overlap most of that feature set and allow me to focus on a specific goal.

Math support is on the radar for this exact reason.
