### ISSUE TITLE
Modify some ligatures

### ISSUE THREAD

**Issue by akhilesh-balaji** [ofolis/consolig#14]
This is a really cool font, but there are a few things that look a bit odd. It would be nice if you could correct a few of them.

## `**`
The star-star ligature for markdown should be pushed down a little. This is how it currently is:

![image](https://user-images.githubusercontent.com/69246693/98195612-2ee81480-1f48-11eb-9314-54124411ccff.png)

And this is how I think it should be:

![image](https://user-images.githubusercontent.com/69246693/98195655-46bf9880-1f48-11eb-88cc-9d3ae1331379.png)

## `\`
The backlashes in escape sequences should be thinner.

## `>=` and `<=`
I think that the lines below the operators should be parallel to the bottom of the ">" line instead of flat. So instead of this:
![image](https://user-images.githubusercontent.com/69246693/98196468-36102200-1f4a-11eb-90a7-b76223c98719.png)

More like this:
![image](https://user-images.githubusercontent.com/69246693/98196483-43c5a780-1f4a-11eb-91c6-8b8ac10fd0eb.png)

## `&&`
This ligature, I think, is used mainly in JS. Consolig has this:
![image](https://user-images.githubusercontent.com/69246693/98196634-a3bc4e00-1f4a-11eb-83df-7b4be7febba7.png)

While all the other programming fonts have this kind of ligature:
![image](https://user-images.githubusercontent.com/69246693/98196609-9737f580-1f4a-11eb-9f7e-8364c24e8fbd.png)

That's all the ligatures I think need improvement.

Other than that, this is a fab font, and I really look forward to using it as an alternative for Fira Code, which, I think, doesn't look as great.

Also, please find attached a text file with all the Fira Code ligatures. There are quite a lot, but it would be nice if all of them were present in Consolig.

[ligatures.txt](https://github.com/ofolis/consolig/files/5491948/ligatures.txt)

If you think that the above changes aren't worth making, then please create a stylistic alternate that has these changes.

**Comment by DrPepperBianco** [comment]
Personally, I would prefer ≤ and ≥ with a horizontal line (like it is now) than with a diagonal line. The same is true for the double ampersand. I like Consolas especially for it cleaner look compared to some of the other fonts (or is it type faces?).

Anyway, maybe the build script could have parameters, so that you can have different designs, and compile the one you prefer.

**Comment by ofolis** [comment]
Good idea @DrPepperBianco ! I am gonna round back here and give Consolig some TLC soon, I've been a little consumed with other projects at the moment. Thanks for the feedback!!!

**Comment by ofolis** [comment]
Update for you guys: I'm working on the standard-res display bugs at the moment, but this is on the radar still as well.

**Comment by ofolis** [comment]
Hey all, got a big win out in https://github.com/ofolis/consolig/releases/tag/v0.4.0 with the main TrueType building. I'll be looking into this stuff next.

In the mean time, if you have a lower-res display, you should see some solid improvements.

**Comment by ofolis** [comment]
v0.5.0 is fully redesigned and properly hinted. Give it a try and let me know if this can be closed. It also supports stylistic alternatives, so have a look at the revised readme for that info.

**Comment by akhilesh-balaji** [comment]
@ofolis Thank you! However, for the stylistic alternates, I wasn't sure about where to specify them. Is it on the command line, or any other file? It wasn't mentioned in the README.md.

Also, what exactly does `ss07` do? The README mentioned "enables regexp matching", but what exactly does it do?

But v0.5.0 is a very cool update, thank you for working on it!

**Comment by ofolis** [comment]
@akhilesh-balaji the process of enabling the stylistic alternatives is dependent upon the environment that you are using. For example, here is documentation provided by FiraCode that describes how to enable them on VSCode:
https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions#stylistic-sets

As for `ss07`, take a look at the explanation on the FiraCode readme. I have matched their functionality for `ss07`.
https://github.com/tonsky/FiraCode

I'll add more instruction around the stylistic alternatives soon!

**Comment by akhilesh-balaji** [comment]
@ofolis thank you, I'll look into it!

**Comment by akhilesh-balaji** [comment]
@ofolis the styles work perfectly, thank you. I think this issue can be closed now.
