### ISSUE TITLE
Make >> the same height as >

### ISSUE THREAD

**Issue by th-bu** [ofolis/consolig#16]
I'll just let the screenshot do the talking :)

![grafik](https://user-images.githubusercontent.com/2885473/102405247-22e07f80-3fe9-11eb-8798-767cfaf00cd5.png)

In those situations the >> looks really akward.

**Comment by th-bu** [comment]
Interesting, this only happens at font size 9. At 10 it's the same height.

**Comment by ofolis** [comment]
I _think_ that I have a fix in the works for this. This is a result of a lack of TrueType instructions on the glyph. More soon -- this is what I'm working on at the moment.

**Comment by ofolis** [comment]
Been a few days, but I had a breakthrough. I can now apply TT instructions to Consolas (which will fix this issue). I now just need to learn how to craft the TT instructions effectively. More soon.

**Comment by ofolis** [comment]
![image](https://user-images.githubusercontent.com/768539/103724578-a49d4a80-4fa2-11eb-997f-e892300aa4f8.png)

So this is how the brackets will look in the upcoming release. It's using the existing geometry, but with my fixes to the font hinting code, it already looks a bit better.

I can also revisit the base geometry if everyone thinks it still needs some work. Should have a release ready to go within the week.

**Comment by ofolis** [comment]
Hokay, @Jeddix -- let me know if https://github.com/ofolis/consolig/releases/tag/v0.4.0 solves the issue.

**Comment by th-bu** [comment]
Works perfectly now in Visual Studio 2019 with font size 9.

![grafik](https://user-images.githubusercontent.com/2885473/103809298-93634500-5059-11eb-97ae-04eb167bb746.png)

The >> still looks funny in that context but I guess you can keep it like that for the C++ guys 😄.

**Comment by ofolis** [comment]
Awesome, and yeah, I hear you re: funkiness. I'll be working on trying to get more customization baked into the builder in the next release.
