### ISSUE TITLE
<> not rendering properly

### ISSUE THREAD

**Issue by akhilesh-balaji** [ofolis/consolig#17]
I'm not sure if this is supposed to be the case, but the `<>` ligature now renders like this:
![image](https://user-images.githubusercontent.com/69246693/103857250-1f1db580-50dc-11eb-9a8e-26517b5bd7e2.png)

Is this intentional?

**Comment by ofolis** [comment]
Didn't know this, but expected as much. This is more of an issue of defining the TT hinting for all my custom glyphs (which I have only done for `===` and `!==`). Sorry about this, I rushed out the 0.4 release to iterate the project and didn't comprehensively test the other glyphs.

If it's any consolation, I'm actively working on another release now. I'm going to be revising the existing glyphs and putting us on a roadmap for feature parity with FiraCode.

**Comment by ofolis** [comment]
![image](https://user-images.githubusercontent.com/768539/104039820-dc73e000-51a4-11eb-91c0-c0a52f94856f.png)
Haha yeah that looks like crap. Whoops...

**Comment by ofolis** [comment]
v0.5.0 has proper hinting for all glyphs. Give it a go and lemme know if this is resolved.

**Comment by akhilesh-balaji** [comment]
Yep, it's been fixed. Thank you!
