### ISSUE TITLE
Kerning problem with /></ in xml

### ISSUE THREAD

**Issue by th-bu** [ofolis/consolig#22]
With the new 0.6.3 version of Consolig it seems there is a kerning problem with `/></`

![grafik](https://user-images.githubusercontent.com/2885473/109429117-6fd5ce80-79fa-11eb-93e9-a70099fabff7.png)

The top row is with standard Consolas, the bottom one is with Consolig.

**Comment by ofolis** [comment]
On it, I'll fix this now

**Comment by th-bu** [comment]
Working fine now, thanks for the fix.
