### ISSUE TITLE
0.6.4 build error

### ISSUE THREAD

**Issue by rescenic** [ofolis/consolig#24]
I used Python 3.9.2 x64. The errors are missing input files, but I have already set them up.
![missing fonts](https://i.ibb.co/72sbWmc/13-03-2021-1186-05-37-04.png)

**Comment by ofolis** [comment]
My guess is that its one of these:
- Something is different between Python 3.8 and 3.9
- You aren't running the `build.py` script while in its directory (though I don't know if this matters)
- You have a directory mismatch somehow in what you're seeing versus what you're executing
- There is some other permissions issue

I wish I could be more help, but this is basic file reading via Python:
- https://github.com/ofolis/consolig/blob/main/build.py#L14
- https://github.com/ofolis/consolig/blob/main/build.py#L50
- https://github.com/ofolis/consolig/blob/main/build.py#L54

On that last line (54), it _COULD_ be giving you a bad error message if -- somehow -- you are missing the source files in the `src` directory. You'll need to clone the whole repo to get it to build correctly.

**Comment by rescenic** [comment]
Thank you for your explanation. I'll try them all.
